spring:
  profiles:
    default: prod
  output:
    ansi:
      enabled: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    open-in-view: true

  redis:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8

  # file upload max size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    import: aws.yml, oauth2.yml, spotify.yml

# SdkClientException 에러 로그 제거
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

# Swagger
springdoc:
  packages-to-scan: com.negongal.hummingbird
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api-docs
    groups:
      enabled: 'true'
  swagger-ui:
    path: swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
  cache:
    disabled: 'true'