spring:
  output:
    ansi:
      enabled: always

  h2:
    console:
      enabled: true
      path: /h2

# spring boot 2.5.x
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  jpa:
    defer-datasource-initialization: true
    # hibernate
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/hummingbird
    username: sa

  # file upload max size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    import: application-aws.yml, application-oauth2.yml, config.yml, application-local.yml


#logging:
#  level:
#    org:
#      hibernate:
#        sql: debug
#        type: trace

# SdkClientException 에러 로그 제거
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error