server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    generate-ddl: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hummingbird
    username: root
    password: hummingbird

  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/oauth/callback/kakao
          google:
            redirect-uri: http://localhost:8080/oauth/callback/google

#logging:
#  level:
#    org:
#      hibernate:
#        sql: debug
#        type: trace